CREATE DATABASE IF NOT EXISTS `test`;

-- Create table;
CREATE TABLE IF NOT EXISTS `test`.`test` (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    str VARCHAR(65)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;